# Generated by Django 4.1.5 on 2023-01-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="prefix",
            field=models.TextField(blank=True, max_length=64),
        ),
    ]
