# Generated by Django 4.1.5 on 2023-01-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mastodon_server",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
